export interface VastOffer {
  id: number;
  ask_contract_id?: number;
  bundle_id?: number;
  bundled_results?: unknown | null;
  bw_nvlink?: number;
  compute_cap?: number;
  cpu_arch?: string;
  cpu_cores?: number;
  cpu_cores_effective?: number;
  cpu_ghz?: number;
  cpu_name?: string;
  cpu_ram?: number;
  credit_discount_max?: number;
  cuda_max_good?: number;
  direct_port_count?: number;
  disk_bw?: number;
  disk_name?: string;
  disk_space?: number;
  dlperf?: number;
  dlperf_per_dphtotal?: number;
  dph_base?: number;
  dph_total?: number;
  driver_version?: string;
  driver_vers?: number;
  duration?: number;
  end_date?: number;
  external?: unknown | null;
  flops_per_dphtotal?: number;
  geolocation?: string;
  geolocode?: number;
  gpu_arch?: string;
  gpu_display_active?: boolean;
  gpu_frac?: number;
  gpu_ids?: number[];
  gpu_lanes?: number;
  gpu_mem_bw?: number;
  gpu_name?: string;
  gpu_ram?: number;
  gpu_total_ram?: number;
  gpu_max_power?: number;
  gpu_max_temp?: number;
  has_avx?: number;
  host_id?: number;
  hosting_type?: number;
  hostname?: string | null;
  inet_down?: number;
  inet_down_cost?: number;
  inet_up?: number;
  inet_up_cost?: number;
  is_bid?: boolean;
  logo?: string;
  machine_id?: number;
  min_bid?: number;
  mobo_name?: string;
  num_gpus?: number;
  os_version?: string;
  pci_gen?: number;
  pcie_bw?: number;
  public_ipaddr?: string;
  reliability?: number;
  reliability_mult?: number;
  rentable?: boolean;
  rented?: boolean;
  score?: number;
  start_date?: number | null;
  static_ip?: boolean;
  storage_cost?: number;
  storage_total_cost?: number;
  total_flops?: number;
  verification?: string;
  vericode?: number;
  vram_costperhour?: number;
  webpage?: string | null;
  vms_enabled?: boolean;
  expected_reliability?: number;
  is_vm_deverified?: boolean;
  resource_type?: string;
  cluster_id?: number | null;
  avail_vol_ask_id?: number;
  avail_vol_dph?: number;
  avail_vol_size?: number;
  rn?: number;
  dph_total_adj?: number;
  reliability2?: number;
  discount_rate?: number;
  discounted_hourly?: number;
  discounted_dph_total?: number;
  search?: {
    gpuCostPerHour?: number;
    diskHour?: number;
    totalHour?: number;
    discountTotalHour?: number;
    discountedTotalPerHour?: number;
  };
  instance?: {
    gpuCostPerHour?: number;
    diskHour?: number;
    totalHour?: number;
    discountTotalHour?: number;
    discountedTotalPerHour?: number;
  };
  time_remaining?: string;
  time_remaining_isbid?: string;
  internet_up_cost_per_tb?: number;
  internet_down_cost_per_tb?: number;
  [key: string]: unknown;
}

export interface VastSearchResponse {
  success?: boolean;
  offers?: VastOffer[];
}


